main = "dist/worker/index.js"
name = "bff"
account_id = "66ea53c74698312c581000b3772b8304"
workers_dev = true
compatibility_date = "2022-01-28"
compatibility_flags = ["streams_enable_constructors"]

[site]
bucket = "dist/client"

[build]
command = "yarn && yarn build"

#[build.upload]
#format = "modules"
#main = "./worker.mjs"